### ISSUE TITLE
No JavaScript found

### ISSUE THREAD

**Issue by mxhit** [raunackt/Rust-Exercism#1]
Why no JavaScript? 🥴

**Comment by mxhit** [comment]
![image](https://media.giphy.com/media/10yXFkBJ0MwGQ0/giphy.gif)

**Comment by raunackt** [comment]
No Javascript yet* 
![image](https://user-images.githubusercontent.com/37471927/185742155-56bbeeb6-85ec-497d-8e63-82cf405582d6.png)
